### ISSUE TITLE
Clarify that passing a string to createElement looks for HTML tags

### ISSUE THREAD

**Issue by eeue56** [danprince/learn-react#1]
From [Exercise 1](https://github.com/danprince/learn-react/blob/gh-pages/lessons/ex1.md) -

> Notice that we wrote Greeting not 'Greeting'. There's a very good reason for this. React doesn't know about any HTML tags called <Greeting>. Since we wrote var Greeting = React.createClass(...) our component lives inside a variable called Greeting. All we need to do is pass this variable to React.render.

I think it would probably be useful to explain the fact that strings arguments are expected to be tag names, otherwise it's a class from React. Just linking to the [docs](https://facebook.github.io/react/docs/top-level-api.html#react.createelement) earlier in the page might get rid of this issue entirely though, since readers can quickly look at the function docs straight while reading. Explicit over implicit and all that.

**Comment by danprince** [comment]
Yeah, definitely a good shout. Probably going to leave some kind of reminder in at that point though. As it's especially confusing if you come from Angular directives, where everything is a string.
