### ISSUE TITLE
Keep the level of knowledge expected consistent

### ISSUE THREAD

**Issue by eeue56** [danprince/learn-react#2]
In [ex2](https://github.com/danprince/learn-react/blob/gh-pages/lessons/ex2.md) you explain what the ternary operator is and how it works. I feel like either you should expect your readers to understand JS syntax enough to be familiar with it, or you should also explain things like objects. I don't think you'll get many beginners trying to use React just from your tutorials - they'll be either experienced in JS already or following a JS guide at the same time

**Comment by danprince** [comment]
Nah, I think the ternary operator is enough of a curveball to warrant explaining - as an exception. Especially considering how prevalent it is in React projects, compared to when you look for it elsewhere in the world of JS (as opposed to objects, which you're going to find universally).

**Comment by eeue56** [comment]
Maybe change it to just be a link on it instead of three sentences. 

> We use the conditional operator here, to help keep things concise. If you aren't familiar read about it here (some link) 

over

> We use the conditional operator here, to help keep things concise. If you aren't already familiar with it, here's a quick breakdown.
> condition ? value_if_true : value_if_false.
> Unlike an if statement, this operator actually returns a value. This is often useful when working with React components.

Just feels like the flow breaks a little bit
