### ISSUE TITLE
The color for quotes on your site is a bit unreadable

### ISSUE THREAD

**Issue by eeue56** [danprince/learn-react#4]
From [here](http://danprince.github.io/learn-react/lessons/ex4.html) the quote for JSX heroing hurts my eyes. Might just be weird laptop screen though, but worth checking

**Comment by danprince** [comment]
Color or the italics? To me the color is fine, but on a big screen the combo of italics and `-1px` letter spacing makes it a bit grim. Fiddle both and try a darker color, see if you find something that works.

**Comment by eeue56** [comment]
Yeah, it's the letter spacing plus italics. Looks pretty good and quote-y with letter-spacing: 1px and blockquote color #3A3A3A

**Comment by danprince** [comment]
Give me one of dem sweet, sweet pull requests. And we'll be finished here.
